# Generated by Django 4.2.5 on 2023-09-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=40)),
                ('Middle_Name', models.CharField(max_length=40)),
                ('Last_Name', models.CharField(max_length=40)),
                ('Mobile_Number', models.CharField(max_length=14)),
                ('Gender', models.CharField(max_length=10)),
                ('Age', models.IntegerField()),
                ('Address', models.CharField(max_length=200)),
                ('Pin_Code', models.IntegerField()),
            ],
        ),
    ]
